services:
  - type: web
    name: identifai-backend
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    branch: main
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: "8000"

  - type: web
    name: identifai-frontend
    runtime: docker
    dockerfilePath: ./frontend/Dockerfile
    dockerContext: ./frontend
    branch: main
    envVars:
      - key: PORT
        value: "8501"
