from enum import StrEnum


class FieldName(StrEnum):
    SIRET = "siret"
    SIRET_EMETTEUR = "siret_emetteur"
    SIRET_CLIENT = "siret_client"
    SIREN = "siren"
    TVA = "tva"
    IBAN = "iban"
    BIC = "bic"
    MONTANT_HT = "montant_ht"
    MONTANT_TTC = "montant_ttc"
    MONTANT_TVA = "montant_tva"
    MONTANT = "montant"
    TVA_RATE = "tva_rate"
    CHIFFRE_AFFAIRES_DECLARE = "chiffre_affaires_declare"
    DATE_EMISSION = "date_emission"
    DATE_EXPIRATION = "date_expiration"
    DATE_PAIEMENT = "date_paiement"
    DATE_VALIDITE = "date_validite"
    DATE_DECLARATION = "date_declaration"
    DATE_DELIVRANCE = "date_delivrance"
    DATE_INSCRIPTION = "date_inscription"
    DATE_PRESTATION = "date_prestation"
    PERIODE = "periode"
    INVOICE_ID = "invoice_id"
    PAYMENT_ID = "payment_id"
    REFERENCE_FACTURE = "reference_facture"
    REFERENCE_PAIEMENT = "reference_paiement"
    METHODE = "methode"
    NOM_EMETTEUR = "nom_emetteur"
    NOM_CLIENT = "nom_client"
    NUMERO = "numero"
    COMPANY_NAME = "company_name"
    TITULAIRE = "titulaire"
    BANK_NAME = "bank_name"
    RCS = "rcs"
    STATUT_PAIEMENT = "statut_paiement"
    EMETTEUR = "emetteur"
    DESTINATAIRE = "destinataire"
